const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const bookingSchema = new Schema({
  // booking id is auto-generated by MongoDB
  movieID: { type: String, required: false },
  movieTitle: { type: String, required: false },
  screeningNum: { type: String, required: false },
  screeningDateTime: { type: Date, required: false },
  firstName: { type: String, required: false },
  lastName: { type: String, required: false },
  seatsBooked: { type: Number, required: false },
  // TODO: make numbers of adult/child/concession match seatsBooked
  adult: { type: Number, required: false },
  child: { type: Number, required: false },
  concession: { type: Number, required: false },
  totalCost: { type: String, required: false },
  paymentID: { type: String, required: false },
});

const bookingModel = mongoose.model("bookings", bookingSchema);
module.exports = bookingModel;
