const { Decimal128 } = require("bson");
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const bookingSchema = new Schema({
  // booking id is auto-generated by MongoDB
  movieID: { type: String, required: true },
  movieTitle: { type: String, required: true },
  screeningDateTime: { type: DataView, required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  // TODO: make only one of adult/child/concession is 'true'
  adult: { type: Boolean, required: false },
  child: { type: Boolean, required: false },
  concession: { type: Boolean, required: false },
  paymentID: { type: String, required: true },
});

const bookingModel = mongoose.model("bookings", bookingSchema);
module.exports = bookingModel;
